version: "3.9"
services:
  client:
    image: grzybolevsky/eshop-client
    ports:
      - "80:80"
  web-api:
    image: grzybolevsky/eshop-api
    ports:
      - "8080:8080"
    volumes:
      - db_volume:/db/
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
volumes:
  db_volume: {}