name: CI/CD pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Set up JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: "18"
          distribution: "temurin"
          cache: "gradle"
      - name: Test
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: test
          gradle-version: 7.5.1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Build Docker Image with Gradle/Jib
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: jib --image=grzybolevsky/eshop-api
          gradle-version: 7.5.1
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername }}
          password: ${{ secrets.AzureAppService_ContainerPassword }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'eshop'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          images: '${{ secrets.AzureAppService_ContainerUsername }}/eshop:${{ github.sha }}'