name: CI/CD pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
      - name: Set up JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: "18"
          distribution: "temurin"
          cache: "gradle"
      - name: Test
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: test
          gradle-version: 7.5.1
      - name: Build Docker Image with Gradle/Jib
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: jib --image=grzybolevsky/eshop-api
          gradle-version: 7.5.1