# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ebusiness-eshop-api

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Set up JDK
        uses: actions/setup-java@v3.5.0
        with:
          java-version: "18"
          distribution: "temurin"
          cache: "gradle"
      - name: Test
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: test
          gradle-version: 7.5.1

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_2a9cc39d179c40c8a82555812d4a7da7 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_6f3543abd1ab4c81bf562e2ffbd6d9a8 }}

      - name: Build Docker Image with Gradle/Jib
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: jib --image=grzybolevsky/eshop-api:${{ github.sha }}
          gradle-version: 7.5.1

      - name: Push
        run: |
          docker push grzybolevsky/eshop-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ebusiness-eshop-api'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_f3669a1bc3bb44859845d5885eef38d8 }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2a9cc39d179c40c8a82555812d4a7da7 }}/grzybolevsky/eshop-api:${{ github.sha }}'